<!-- SocialShare - Facebook Comments -->
<div class="fbCommentsContainer" style="min-height:160px;">
	<div class="fb-comments" data-href="<?php echo $this->helper('core/url')->getCurrentUrl();?>" data-num-posts="<?php echo Mage::getStoreConfig('facebookcomments/conf/posts'); ?>" data-width="<?php echo Mage::getStoreConfig('facebookcomments/conf/width'); ?>" data-colorscheme="<?php echo Mage::getStoreConfig('facebookcomments/conf/colorscheme'); ?>"></div>
</div>
<!-- SocialShare - Facebook Comments END -->
